/* ADAKU lyrics — paste each song's words between the backticks. */

window.ADAKU_LYRICS = {
  "Loving Grace": ``,
  "Tactile Illusion": ``,
  "Synthetic Intimacy": ``,
  "Modelling ME / Modelling YOU": ``,
  "NeuraLinked": ``,
  "Love You": ``,
  "Quantum Nostalgia (enigmatic)": ``,
  "Quantum Nostalgia (hypnotic)": ``,
  "Synthetic Hollywood": ``,
  "'SIM_Ancestor_": ``,
  "Copy Paste Life": ``,
  "Silent Orbit": ``,
  "Tomorrow's Speed": ``,
  "Proxy Presence": ``,
  "Color of Your Smile": ``,
  "Social Gravity": ``,
  "Abundance Mirror": ``,
  "Amber Parallax": ``,
  "Green Dot Midnight": ``,
  "Solastalgia": ``,
  "UnFairytale": ``,
  "Parallel Worlds": ``,
  "Wild & Free": ``,
  "MissionX": ``,
  "Mega Brain": ``,
  "Car Door Slam": ``,
  "Messy Love": ``,
  "Midnight Eyes": ``,
  "Why Don't You Come?": ``,
  "Burn the Old Letters": ``,
  "Lord of the Mist": ``,
};
